name: "Scrypted"
version: "0.0.163"
slug: scrypted
description: "A home automation platform powered by node.js"
arch:
  - aarch64
  - amd64
  - armv7
image: koush/scrypted
host_network: true
environment:
  SCRYPTED_VOLUME: "/config/scrypted"
backup_exclude:
  - /server
webui: "https://[HOST]:[PORT:10443]"
stage: experimental
advanced: true
map:
  - config:rw
