name: "Scrypted"
version: "18-bullseye-full-v0.5.12"
slug: scrypted
description: "A home automation platform powered by node.js"
url: "https://github.com/koush/scrypted"
arch:
  - aarch64
  - amd64
  - armv7
image: koush/scrypted
host_network: true
environment:
  SCRYPTED_VOLUME: "/data/scrypted_data"
backup_exclude:
  - /server
webui: "https://[HOST]:[PORT:10443]"
stage: experimental
advanced: true
init: false
hassio_role: default
