name: Scrypted
version: "v0.6.10-1"
slug: scrypted
description: A home automation platform powered by node.js
url: "https://github.com/koush/scrypted"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:memory
hassio_api: true
ingress_stream: true
host_network: true
usb: true
image: "ghcr.io/aegjoyce/{arch}-ha-addon-scrypted"
environment:
  SCRYPTED_VOLUME: "/data/scrypted_data"
backup_exclude:
  - /server
