name: Scrypted Thin
version: "v0.6.9"
slug: scrypted-thin
description: Thin version of Scrypted with smaller image size and some dependencies removed
url: "https://github.com/koush/scrypted"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:memory
hassio_api: true
ingress_stream: true
image: "ghcr.io/aegjoyce/{arch}-ha-addon-scrypted-thin"
environment:
  SCRYPTED_VOLUME: "/data/scrypted_data"
backup_exclude:
  - /server
#  SCRYPTED_HTTPS_OPTIONS_FILE: "/config/data_scrypted/options.json"
#ports:
#  10444/tcp: 10444
#ports_description:
#  10444/tcp: "Homekit"
