name: Scrypted Thin
version: "v0.6.16"
slug: scrypted-thin
description: Thin version of Scrypted with smaller image size and some dependencies removed
url: "https://github.com/koush/scrypted"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 0
panel_icon: mdi:memory
hassio_api: true
ingress_stream: true
host_network: true
usb: true
image: "ghcr.io/aegjoyce/{arch}-ha-addon-scrypted-thin"
environment:
  SCRYPTED_VOLUME: "/data/scrypted_data"
backup_exclude:
  - /server
