name: Update Scrypted Thin
on:
  schedule:
    - cron: 0,5,10 12 * * *
  workflow_dispatch:
jobs:
  Get-Remote-Version-Bump:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag
        id: latest
        run: |
          echo "tag=$( \
          curl https://hub.docker.com/v2/repositories/koush/scrypted/tags?count=1000 \
          | jq -r '[.results | sort_by(.last_updated) | reverse[] | select(.name | startswith("18-bullseye-thin-"))][0] | .name | ltrimstr("18-bullseye-thin-")')" >> $GITHUB_OUTPUT
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Check out repository code
        uses: actions/checkout@v3.4.0
      - name: ðŸ— Set up yq
        uses: frenck/action-setup-yq@v1
      - name: Get current version with hotfixes
        id: current-hotfix
        run: echo "tag=$(yq '.version' ${{ github.workspace }}/scrypted-thin/config.yaml)" >> $GITHUB_OUTPUT
      - name: Strip out hotfix version
        env:
          TAG: ${{ steps.current-hotfix.outputs.tag }}
        id: current
        run: echo "tag=${TAG%-*}" >> $GITHUB_OUTPUT
      - uses: madhead/semver-utils@latest
        id: version
        with:
          # A version to work with
          version: ${{ steps.current.outputs.tag }}
          # A version to compare against
          compare-to: ${{ steps.latest.outputs.tag }}
      - name: If newer tag available, bump the version
        if: ${{ steps.version.outputs.comparison-result == '<' }}
        shell: bash
        run: |
          yq -i '.version = "${{ steps.latest.outputs.tag }}"' ${{ github.workspace }}/scrypted-thin/config.yaml
      - name: If newer tag available, bump the package version
        if: ${{ steps.version.outputs.comparison-result == '<' }}
        shell: bash
        run: |
          yq -i '.labels."org.opencontainers.image.version" = "${{ steps.latest.outputs.tag }}"' ${{ github.workspace }}/scrypted-thin/build.yaml
      - name: If newer tag available, bump the dockerfile
        if: ${{ steps.version.outputs.comparison-result == '<' }}
        run: |
          sed -i "s/${{ steps.current.outputs.tag }}/${{ steps.latest.outputs.tag }}/g" ${{ github.workspace }}/scrypted-thin/Dockerfile
      - uses: actions/setup-python@v4
        if: ${{ steps.version.outputs.comparison-result == '<' }}
        with:
          python-version: "3.10.4"
      - name: If newer tag available, bump the changelog
        if: ${{ steps.version.outputs.comparison-result == '<' }}
        run: |
          sed -i  "7i \## [${{ steps.latest.outputs.tag }}] - ${{ steps.date.outputs.date }}\n### Changed\n- Update base image to ${{ steps.latest.outputs.tag }}\n" ${{ github.workspace }}/scrypted-thin/CHANGELOG.md
      - name: Create Pull Request
        if: ${{ steps.version.outputs.comparison-result == '<' }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Bump Scrypted Thin to ${{ steps.latest.outputs.tag }}
          title: Bump Scrypted Thin to ${{ steps.latest.outputs.tag }}
          branch: create-pull-request/scrypted-thin
